// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: DeviceInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct DeviceInfo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// E.g., Samsung Galaxy S22, iPhone14,3
  var model: String = String()

  /// E.g., Android 13, iOS 16.0
  var platform: String = String()

  /// For web
  var userAgent: String {
    get {return _userAgent ?? String()}
    set {_userAgent = newValue}
  }
  /// Returns true if `userAgent` has been explicitly set.
  var hasUserAgent: Bool {return self._userAgent != nil}
  /// Clears the value of `userAgent`. Subsequent reads from it will return its default value.
  mutating func clearUserAgent() {self._userAgent = nil}

  var type: DeviceInfo.DeviceType = .unknown

  /// E.g., AT&T
  var carrier: String {
    get {return _carrier ?? String()}
    set {_carrier = newValue}
  }
  /// Returns true if `carrier` has been explicitly set.
  var hasCarrier: Bool {return self._carrier != nil}
  /// Clears the value of `carrier`. Subsequent reads from it will return its default value.
  mutating func clearCarrier() {self._carrier = nil}

  var vendorID: String {
    get {return _vendorID ?? String()}
    set {_vendorID = newValue}
  }
  /// Returns true if `vendorID` has been explicitly set.
  var hasVendorID: Bool {return self._vendorID != nil}
  /// Clears the value of `vendorID`. Subsequent reads from it will return its default value.
  mutating func clearVendorID() {self._vendorID = nil}

  var advertiserID: String {
    get {return _advertiserID ?? String()}
    set {_advertiserID = newValue}
  }
  /// Returns true if `advertiserID` has been explicitly set.
  var hasAdvertiserID: Bool {return self._advertiserID != nil}
  /// Clears the value of `advertiserID`. Subsequent reads from it will return its default value.
  mutating func clearAdvertiserID() {self._advertiserID = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum DeviceType: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case unknown // = 0
    case mobile // = 1
    case tablet // = 2
    case desktop // = 3
    case tv // = 4
    case watch // = 5
    case automotive // = 6
    case UNRECOGNIZED(Int)

    init() {
      self = .unknown
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unknown
      case 1: self = .mobile
      case 2: self = .tablet
      case 3: self = .desktop
      case 4: self = .tv
      case 5: self = .watch
      case 6: self = .automotive
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unknown: return 0
      case .mobile: return 1
      case .tablet: return 2
      case .desktop: return 3
      case .tv: return 4
      case .watch: return 5
      case .automotive: return 6
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}

  fileprivate var _userAgent: String? = nil
  fileprivate var _carrier: String? = nil
  fileprivate var _vendorID: String? = nil
  fileprivate var _advertiserID: String? = nil
}

#if swift(>=4.2)

extension DeviceInfo.DeviceType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [DeviceInfo.DeviceType] = [
    .unknown,
    .mobile,
    .tablet,
    .desktop,
    .tv,
    .watch,
    .automotive,
  ]
}

#endif  // swift(>=4.2)

#if swift(>=5.5) && canImport(_Concurrency)
extension DeviceInfo: @unchecked Sendable {}
extension DeviceInfo.DeviceType: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension DeviceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "DeviceInfo"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "model"),
    2: .same(proto: "platform"),
    3: .standard(proto: "user_agent"),
    4: .same(proto: "type"),
    5: .same(proto: "carrier"),
    6: .standard(proto: "vendor_id"),
    7: .standard(proto: "advertiser_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._userAgent) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._carrier) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._vendorID) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._advertiserID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 1)
    }
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 2)
    }
    try { if let v = self._userAgent {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    if self.type != .unknown {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 4)
    }
    try { if let v = self._carrier {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._vendorID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._advertiserID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DeviceInfo, rhs: DeviceInfo) -> Bool {
    if lhs.model != rhs.model {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs._userAgent != rhs._userAgent {return false}
    if lhs.type != rhs.type {return false}
    if lhs._carrier != rhs._carrier {return false}
    if lhs._vendorID != rhs._vendorID {return false}
    if lhs._advertiserID != rhs._advertiserID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DeviceInfo.DeviceType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN"),
    1: .same(proto: "MOBILE"),
    2: .same(proto: "TABLET"),
    3: .same(proto: "DESKTOP"),
    4: .same(proto: "TV"),
    5: .same(proto: "WATCH"),
    6: .same(proto: "AUTOMOTIVE"),
  ]
}
